version: '3.8'

services:
  ragfab-backend:
    build:
      context: .
      dockerfile: coolify/2-backend/Dockerfile
    container_name: ragfab-backend
    environment:
      # Base de données PostgreSQL (URL HTTPS ou connexion directe)
      DATABASE_URL: ${DATABASE_URL:-postgresql://raguser:ragpass123@ragfab-postgres:5432/ragdb}

      # API Embeddings (URL HTTPS)
      EMBEDDINGS_API_URL: ${EMBEDDINGS_API_URL:-http://ragfab-embeddings:8001}
      EMBEDDING_DIMENSION: ${EMBEDDING_DIMENSION:-1024}

      # JWT et authentification
      JWT_SECRET: ${JWT_SECRET:-your-secret-key-change-in-production}
      ADMIN_USERNAME: ${ADMIN_USERNAME:-admin}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin}

      # Mistral API
      MISTRAL_API_KEY: ${MISTRAL_API_KEY:-}
      MISTRAL_API_URL: ${MISTRAL_API_URL:-https://api.mistral.ai}
      MISTRAL_MODEL_NAME: ${MISTRAL_MODEL_NAME:-mistral-small-latest}

      # Chocolatine API (optionnel)
      CHOCOLATINE_API_URL: ${CHOCOLATINE_API_URL:-https://apigpt.mynumih.fr}
      CHOCOLATINE_MODEL_NAME: ${CHOCOLATINE_MODEL_NAME:-jpacifico/Chocolatine-2-14B-Instruct-v2.0.3}

      # CORS - Liste des origines autorisées (frontend)
      CORS_ORIGINS: ${CORS_ORIGINS:-https://ragfab.yourdomain.com,http://localhost:3000}

      # Logs
      LOG_LEVEL: ${LOG_LEVEL:-INFO}

    ports:
      - "8000:8000"
    volumes:
      # Persistance des fichiers uploadés
      - uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  uploads:
    driver: local
