version: '3.8'

services:
  ragfab-postgres:
    build:
      context: ./coolify/4-postgres
      dockerfile: Dockerfile
    container_name: ragfab-postgres
    environment:
      # Credentials PostgreSQL
      POSTGRES_USER: ${POSTGRES_USER:-raguser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ragpass123}
      POSTGRES_DB: ${POSTGRES_DB:-ragdb}

      # Configuration PostgreSQL (locale C.UTF-8 est disponible par défaut)
      POSTGRES_INITDB_ARGS: ${POSTGRES_INITDB_ARGS:--E UTF8 --locale=C.UTF-8}

    # Note: Pas de section ports - accessible uniquement via réseau Docker privé (plus sécurisé)
    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

    # Limites de ressources
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 512M

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-raguser} -d ${POSTGRES_DB:-ragdb}"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - coolify

volumes:
  postgres_data:
    driver: local

networks:
  coolify:
    external: true
    name: coolify
