version: '3.8'

services:
  ragfab-embeddings:
    build:
      context: .
      dockerfile: ./coolify/3-embeddings/Dockerfile
    container_name: ragfab-embeddings
    environment:
      # Modèle d'embeddings (ne pas changer sans recalculer tous les embeddings)
      MODEL_NAME: ${MODEL_NAME:-intfloat/multilingual-e5-large}

      # Cache Hugging Face
      TRANSFORMERS_CACHE: ${TRANSFORMERS_CACHE:-/home/embeddings/.cache/huggingface}

      # Logs
      LOG_LEVEL: ${LOG_LEVEL:-INFO}

    # Note: Pas de section ports - accessible uniquement via réseau Docker privé
    volumes:
      # Persistance du cache du modèle (évite re-téléchargement)
      - model_cache:/home/embeddings/.cache

    restart: unless-stopped

    # Limites de ressources (ajuster selon votre serveur)
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 4G

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

    networks:
      - coolify

volumes:
  model_cache:
    driver: local

networks:
  coolify:
    external: true
    name: coolify
