version: '3.8'

services:
  ragfab-frontend:
    build:
      context: .
      dockerfile: coolify/1-frontend/Dockerfile
    container_name: ragfab-frontend
    environment:
      # URL du backend API (à configurer dans Coolify)
      BACKEND_API_URL: ${BACKEND_API_URL:-https://api.ragfab.yourdomain.com}

    # Note: Pas de section ports - Coolify/Traefik gère le routing via le domaine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

    networks:
      - ragfab-network

networks:
  ragfab-network:
    driver: bridge
    name: ragfab-network
